# Generated by Django 5.0.2 on 2024-02-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
